services:
  - type: web
    name: qaran
    env: node
    region: oregon
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: MONGODB_URI
        value: mongodb+srv://qaranuser:iPyjRkJyr3gaAsX3@qaran-baby-shop.ed8u0jn.mongodb.net/qaran?retryWrites=true&w=majority&appName=Qaran-Baby-Shop
      - key: CORS_ORIGINS
        value: "https://baby-shop-mcqv.vercel.app,https://baby-shop-mcqv-git-master-crookxs-projects.vercel.app"
    autoDeploy: true